# secret.sample.yaml (using stringData)
apiVersion: v1
kind: Secret
metadata:
  name: learnerds-secrets-sample
type: Opaque
stringData:
  DB_USER: "your-postgres-db-name"
  DB_PASSWORD: "your-postgres-password"
  EMAIL_HOST_PASSWORD_USER: "your-email-host-password"
  RABBITMQ_USER: "your-rabbitmq-username"
  RABBITMQ_PASS: "your-rabbitmq-password"
  DJANGO_SECRET_USER: "user-service-django-secret"
  JWT_SECRET_KEY_USER: "your-jwt-secret"
  DJANGO_SECRET_ADMIN: "admin-service-django-secret"
  CLOUDINARY_CLOUD_NAME: "your-cloudinary-cloud-name"
  CLOUDINARY_API_KEY: "your-cloudinary-api-key"
  CLOUDINARY_API_SECRET: "your-cloudinary-api-secret"
  DJANGO_SECRET_COURSE: "course-service-django-secret"
  STRIPE_SECRET_KEY: "your-stripe-secret-key"
  STRIPE_PUBLISHABLE_KEY: "your-stripe-publishable-key"
  STRIPE_WEBHOOK_SECRET: "your-stripe-webhook-secret"
  ZEGO_APP_ID: "your-zego-cloud-app-id"
  ZEGO_SERVER_SECRET: "your-zego-cloud-server-secret"
  DJANGO_SECRET_CHANNEL: "channel-service-django-secret"
  MONGODB_DATABASENAME: "your-mongodb-db-name"
  MONGODB_URI: "your-mongodb-uri"
  MONGODB_USERNAME: "your-mongodb-username"
  MONGODB_PASSWORD: "your-mongodb-password"
  DJANGO_SECRET_GATEWAY: "api-gateway-django-secret"
  FIREBASE_PRIVATE_KEY_ID: "your-firbase-private-key-id"
  FIREBASE_PRIVATE_KEY: "your-firbase-private-key"
  FIREBASE_CLIENT_ID: "your-firbase-client-id"
