apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: learnerds-cert
  namespace: default
spec:
  secretName: learnerds-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api.learnerds.online
