name: CI/CD Pipeline for Django Microservices

on:
  push:
    branches:
      - test_workflow
    paths:
      - 'server/api_gateway_django/**'
      - 'server/user_service/**'
      - 'server/admin_service/**'
      - 'server/course_service/**'
      - 'server/channel_service/**'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_SERVICE_PREFIX_NAME: ${{ vars.DOCKER_SERVICE_PREFIX_NAME }}
  DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: api_gateway_django
            path: server/api_gateway_django
            deployment: api_gateway-deployment.yaml
            port: 8000
          - name: user_service
            path: server/user_service
            deployment: user_service-deployment.yaml
            port: 8001
          - name: admin_service
            path: server/admin_service
            deployment: admin_service-deployment.yaml
            port: 8002
          - name: course_service
            path: server/course_service
            deployment: course_service-deployment.yaml
            port: 8003
          - name: channel_service
            path: server/channel_service
            deployment: channel_service-deployment.yaml
            port: 8004
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Check for changes in ${{ matrix.service.name }}
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changed:
              - '${{ matrix.service.path }}/**'

      - name: Build and push image
        if: steps.changes.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_SERVICE_PREFIX_NAME }}-${{ matrix.service.name }}:${{ env.DOCKER_IMAGE_TAG }} ${{ matrix.service.path }}
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_SERVICE_PREFIX_NAME }}-${{ matrix.service.name }}:${{ env.DOCKER_IMAGE_TAG }}
