name: CI Pipeline for Django Microservices

on:
  push:
    branches:
      - test_workflow
    paths:
      - 'server/api_gateway_django/**'
      - 'server/user_service/**'
      - 'server/admin_service/**'
      - 'server/course_service/**'
      - 'server/channel_service/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_SERVICE_PREFIX_NAME: ${{ vars.DOCKER_SERVICE_PREFIX_NAME }}
  DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: api_gateway_django
            path: server/api_gateway_django
          - name: user_service
            path: server/user_service
          - name: admin_service
            path: server/admin_service
          - name: course_service
            path: server/course_service
          - name: channel_service
            path: server/channel_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in ${{ matrix.service.name }}
        id: changes
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.event.before }}
          filters: |
            changed:
              - '${{ matrix.service.path }}/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changes.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_SERVICE_PREFIX_NAME }}-${{ matrix.service.name }}:${{ env.DOCKER_IMAGE_TAG }} ${{ matrix.service.path }}
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_SERVICE_PREFIX_NAME }}-${{ matrix.service.name }}:${{ env.DOCKER_IMAGE_TAG }}
